# Dependencies
markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      '안녕하세요. 최재만입니다.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# plugins:
plugins: [jekyll-paginate]
paginate: 5
painate_path: "page:num"

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

